### ISSUE TITLE
My local tests are not green lighting in Learn for this ArrayChallenge lab

### ISSUE THREAD

**Issue by yayitserica** [learn-co-curriculum/swift-arrayChallenge-lab#8]
![screen shot 2016-09-05 at 12 54 05 am](https://cloud.githubusercontent.com/assets/15487798/18237775/72662756-7303-11e6-9882-aeed6bfa328d.png)

**Comment by ianrahman** [comment]
@yayitserica Could you please try out the instructions at the following repo and let me know if this solves the issues with the lights?

[Reconnecting Xcode and Learn](https://github.com/learn-co-curriculum/reconnecting-xcode-and-learn)

Thanks!

**Comment by yayitserica** [comment]
Hi Ian,

I added the script line of code and then ran tests again and my Learn green
light didn't light up.

Any other suggestions?

**Comment by ianrahman** [comment]
Hi @yayitserica,

Could you make sure the scheme you edited is selected as "Shared" and let me know if that was the case or not?
![second](http://i.imgur.com/p5HvRmx.png)

**Comment by yayitserica** [comment]
Hi Ian,

Yup, it was "shared".  Here are some screenshots I just took:

**Comment by ianrahman** [comment]
Put the following line of code in the `test_runner.sh` file of your project, somewhere near the top.

`exec > /Users/<YOUR COMPUTER USERNAME HERE>/Desktop/my_log_file.txt 2>&1`

After doing so, run the tests from Xcode and see if the .txt file gets created with contents in it. This should confirm Xcode and `test_runner` are on the same page.

If that file is created successfully, there may be an issue with GitHub authentication we'll try to work through next.

**Comment by yayitserica** [comment]
Hi Ian,

I added the code to the .sh file but the log file wasn't created on my
desktop.  Here's a screenshot of the tests passing, the code in the .sh
file and my terminal (that doesn't have the my_log_file.txt file).

Any other ideas?

Thanks!

**Comment by ianrahman** [comment]
Next idea... Do you have multiple Learn or GitHub accounts? One issue we've noticed is that it's possible the .gitconfig on your computer is linked to an account that doesn't match Learn.

One way to check is to go to http://learn.co/YOUR_USERNAME_HERE (this is your Learn.co profile.)
Right click the email icon at the top of the page and copy the email address to which it's attached. Paste it somewhere for reference. 

Next, open up terminal and from any directory enter the command `git config user.email`, which will bring up the email address your computer is using to connect to GitHub. 

Could you confirm that these two email addresses match? If they don't, we'll remove one of those account from Learn, which should allow you to log in from the other and finally connect all the pieces.

**Comment by yayitserica** [comment]
Hi Ian,

Just checked and I confirm that my Learn.co github email matches what's in
my terminal.  See screenshot.

Any other tips?

Thanks,
E

**Comment by ianrahman** [comment]
Hi Erica,

Sorry for not mentioning this before, but none of your screenshots have been visible. Could you try uploading them directly to this issue on GitHub? 

Thanks,
Ian

**Comment by yayitserica** [comment]
![screen shot 2016-09-06 at 7 59 53 pm](https://cloud.githubusercontent.com/assets/15487798/18318844/390374ce-74f1-11e6-853f-446a3f49d2b9.png)
![screen shot 2016-09-06 at 3 58 43 pm](https://cloud.githubusercontent.com/assets/15487798/18318847/3bd3e6de-74f1-11e6-99ad-012c44231f40.png)
![screen shot 2016-09-06 at 3 58 22 pm](https://cloud.githubusercontent.com/assets/15487798/18318853/3f4e00d8-74f1-11e6-9a51-9da0f5fd7fe1.png)
![screen shot 2016-09-05 at 12 54 05 am](https://cloud.githubusercontent.com/assets/15487798/18318855/4139fd84-74f1-11e6-8ad9-a616117afe50.png)
![screen shot 2016-09-05 at 12 45 48 pm](https://cloud.githubusercontent.com/assets/15487798/18318858/42fba640-74f1-11e6-9571-dc4e49c475b3.png)
![screen shot 2016-09-04 at 2 45 28 pm](https://cloud.githubusercontent.com/assets/15487798/18318861/454f4c76-74f1-11e6-8a8b-b92f7a7d199c.png)

**Comment by yayitserica** [comment]
![screen shot 2016-09-07 at 10 24 16 am](https://cloud.githubusercontent.com/assets/15487798/18318879/542c383a-74f1-11e6-880a-222f5f091004.png)

**Comment by JimCampagno** [comment]
@yayitserica I'm going to make some changes to this lab and get back to you 

I will message you here and let you know of the next steps you need to take.

**Comment by yayitserica** [comment]
Thank you.

**Comment by JimCampagno** [comment]
@yayitserica 

I just made an update to the lab. It _might_ work--if not, let me know.

You will have to delete your forked version and re-clone it down. If you're having trouble re-cloning the lab down after re-forking it AFTER you had removed the older version, let me know.

**Comment by yayitserica** [comment]
It's green now!

**Comment by JimCampagno** [comment]
@yayitserica That makes me happy :)

If you notice any labs giving you that same problem. Raise issues like you did here, ALSO! shoot me an e-mail and let me know. My e-mail is jim@flatironschool.com or mention me in the comment of the issue you're raising @jimcampagno <-- like that
